version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: node_starter
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
     - "8180:8080"
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_NAME: node_starter
      KEYCLOAK_DATABASE_USER: student
      KEYCLOAK_DATABASE_PASSWORD: student

      KEYCLOAK_AUTH_SERVER_URL: http://localhost:8180/auth
    command: [ "start-dev", "--https-key-store-file=/etc/keycloak-keystore.jks", "--https-key-store-password=secret", "--import-realm"]
    volumes:
        - ./keycloak/keycloak-keystore.jks:/etc/keycloak-keystore.jks
        - ./realm-export/:/opt/keycloak/data/import/

